spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/MySql-test?autoReconnect=true&useSSL=false
    username: root
    password: root123
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
