
spring:
    data:
        mongodb:
            database: communityDatabase
            username: rajshri
            password: root
            host: localhost            
            port: 27017
            
