spring:
    data:
        mongodb:
#             uri: mongodb://root:root123@http://172.23.239.122:27017/message_service
            database: message_service
            host: 172.23.239.122
            port: 27017
            password: root123
            username: root
